spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@alswl8671_highTNS_ADMIN=C:/MINJI/Spring/resource/Wallet_alswl8671
#    username: admin
#    password: X9zp9qqhm3bc

    url: jdbc:oracle:thin:@db202108051346_high?TNS_ADMIN=C:/MINJI/Spring/resource/Wallet_DB202108051346
    username: admin
    password: Qkrthals0283!

    mail:
    host: smtp.gmail.com
    port: 587
    email-username: korpg95274@gmail.com
    email-password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

    devtools:
      livereload:
        enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false