spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db202108051346_high?TNS_ADMIN=C:/Users/user/Desktop/dudgns_wallet/Wallet_DB202108051346
    username: admin
    password: Qkrthals0283!

    mail:
    host: smtp.gmail.com
    port: 587
    email-username: korpg95274@gmail.com
    email-password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

    devtools:
      livereload:
        enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false